### ISSUE TITLE
Normals are NaN Vectors

### ISSUE THREAD

**Issue by WojciechTrzesniowski** [Scrawk/Marching-Cubes-On-The-GPU#1]
I experiment with your code. Firstly I provisionally removed perlin noise to work with simply plain or cube. I've just overwritten m_perlinNoise shader result.

```            
float[] verts = new float[SIZE];
m_noiseBuffer.GetData(verts);

for (int z = 0; z < N; z++)
    for (int y = 0; y < N; y++)
        for (int x = 0; x < N; x++)
        {
            verts[x + y * N + z * N * N] = 1;

            if (z < 3)
                verts[x + y * N + z * N * N] = -1;
        }

m_noiseBuffer.SetData(verts);
```

But Igot a black plain. I've checked that all generated vertices have NaN vector normals (using your ReadBackMesh func).

I've also found a clue. This displays a color:
```
float[] verts = new float[SIZE];
m_noiseBuffer.GetData(verts);

for (int z = 0; z < N; z++)
    for (int y = 0; y < N; y++)
        for (int x = 0; x < N; x++)
        {
            verts[x + y * N + z * N * N] = 1;

            if (z == 3)
                verts[x + y * N + z * N * N] = 0.9f;

            if (z < 3)
                verts[x + y * N + z * N * N] = -1;
        }

m_noiseBuffer.SetData(verts);
```

Normals depend on deeper vertices and those have to have different values?

**Comment by Scrawk** [comment]
The normal are calculated using finite difference on a 3D volume which only works if your voxels have a nice gradeint which the Perlin Noise does.

The values you entered won’t have a good gradient for this method and will give nan normals.

Since you basically have a 2d plain you will have change the finite difference 
To work like it’s a 2d height map or something like that.
